# Generated by Django 2.0.5 on 2018-06-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlbi_schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_id', models.CharField(max_length=10)),
                ('target', models.CharField(max_length=100)),
                ('band', models.CharField(max_length=5)),
                ('PI', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=1000)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
