# Generated by Django 2.0.5 on 2018-06-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlbi_schedule', '0002_auto_20180614_0708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='observation_id',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='PI',
            new_name='PI_name',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='target',
            new_name='description',
        ),
        migrations.AddField(
            model_name='schedule',
            name='contact_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
