# Generated by Django 2.0.5 on 2018-06-14 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vlbi_schedule', '0003_auto_20180614_0733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='ID',
            new_name='observation_ID',
        ),
    ]
