# Generated by Django 2.0.5 on 2018-06-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlbi_schedule', '0004_auto_20180614_0734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_ID', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('PI_name', models.CharField(max_length=100)),
                ('contact_name', models.CharField(max_length=100)),
                ('band', models.CharField(max_length=5)),
                ('comment', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
