# Generated by Django 2.0.5 on 2018-06-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlbi_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='comment',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='observation_ID',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
