# Generated by Django 2.0.5 on 2018-06-15 02:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vlbi_schedule', '0002_auto_20180614_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
